### ISSUE TITLE
Question About MAP Method Training Parameters using llama2 on ARC-E

### ISSUE THREAD

**Issue by xuullin** [MaximeRobeyns/bayesian_lora#3]
In my attempt to replicate your results, I found a significant discrepancy between my MAP results and those reported in your paper. I used the initial parameters use_peft=false and prior_var=0.1, but these parameters were not detailed in your paper. 

What initial parameter settings did you use for training the MAP method?

What specific value did you use for use_peft?
What specific value did you use for prior_var?

Thank you very much for your time and assistance. I look forward to your response!

**Comment by MaximeRobeyns** [comment]
Hi,

The research code we to produce the numbers in the paper can be found in [this repository](https://github.com/adamxyang/laplace-lora) from my co-author. The MAP training procedure in the example in my repository was just a quick and simple demonstration to illustrate how to use the library.

Do refer to my co-author's repository for the hyperparameter values and so forth required to reproduce numbers.

Best,
Maxime

**Comment by xuullin** [comment]
Thanks a lot!
