### ISSUE TITLE
Configuration for Reproducing Table 1 Results

### ISSUE THREAD

**Issue by brooksniu** [MaximeRobeyns/bayesian_lora#6]
Dear authors of Laplace-LoRA,

Hi, could you please share the exact configuration for reproducing results in table 1? Some of the testing sets are trimmed to 1500 datapoints, i.e. in `examples/configs/dset/boolq.yaml`. Is this the same configuration used for experiments in the paper?

**Comment by brooksniu** [comment]
Found the laplace-lora repo, closing this

**Comment by John-Wilson-ML** [comment]
> Found the laplace-lora repo, closing this

Dear brooksniu,

Can you tell me where the configuration in Table 1 is for reproducing the results? Can you give me a link to the repository?
